// ⚠️  AUTO-GENERATED by @bettercms-ai/codegen v0.2.0 — DO NOT EDIT.
// Regenerate with: npx @bettercms-ai/codegen
// Source of truth: your BetterCMS content models (the same schema the dashboard
// builder and the MCP tools write). Re-run codegen after any schema change.

/**
 * Rich-text field value returned by the Delivery API.
 *
 * - `format`/`value`: the portable, editor-agnostic payload (Lexical EditorState) —
 *   render it with your editor's serializer for full fidelity.
 * - `html`: server-rendered, sanitized HTML (computed render-on-write). Present on
 *   Delivery reads; the simplest path for non-React consumers — safe to inject directly
 *   (e.g. `dangerouslySetInnerHTML`). Optional: legacy/un-normalized values may omit it.
 *
 * The `{ format, value }` contract is unchanged; `html` is additive.
 */
export type RichText = {
  readonly format: string;
  readonly value: unknown;
  readonly html?: string;
};

/**
 * Image / media field value as stored and returned verbatim by the Delivery API
 * (server-normalized on write to the canonical shape). `url` is always present; an
 * unresolved/external value may carry only `url`. `altText` is the accessibility text
 * for `<img alt>`.
 */
export interface BetterCMSImage {
  readonly id?: string;
  readonly url: string;
  readonly name?: string;
  readonly altText?: string | null;
  readonly width?: number;
  readonly height?: number;
}

/**
 * Delivery envelope around a model's typed `data`. `getEntry`/`listEntries` in the
 * Next adapter return this shape, with `fields` typed by the model.
 */
export interface BetterCMSEntry<TFields> {
  readonly slug: string;
  readonly status: "draft" | "published";
  readonly fields: TFields;
  readonly updatedAt: string;
}

/**
 * About
 * Model slug: `about`
 */
export interface AboutFields {
  /** Eyebrow */
  readonly eyebrow?: string;
  /** Hero Title */
  readonly heroTitle?: string;
  /** Hero Subtitle */
  readonly heroSubtitle?: string;
  /** Hero Image */
  readonly heroImage?: BetterCMSImage;
  /** Story Title */
  readonly storyTitle?: string;
  /** Story */
  readonly story?: RichText;
  /** Values */
  readonly values?: {
    readonly repeatable?: Array<{
      /** Title */
      readonly title?: string;
      /** Body */
      readonly body?: string;
    }>;
  };
  /** Stats */
  readonly stats?: {
    readonly repeatable?: Array<{
      /** Value */
      readonly value?: string;
      /** Label */
      readonly label?: string;
    }>;
  };
  /** Team */
  readonly team?: unknown;
}

/**
 * Author
 * Model slug: `author`
 */
export interface AuthorFields {
  /** Name */
  readonly name?: string;
  /** Role */
  readonly role?: string;
  /** Bio */
  readonly bio?: string;
  /** Avatar */
  readonly avatar?: BetterCMSImage;
}

/**
 * authors
 * Model slug: `authors`
 */
export interface AuthorsFields {
  /** Name */
  readonly name?: string;
  /** Bio */
  readonly bio?: string;
}

/**
 * Blog post
 * Model slug: `blog-post`
 */
export interface BlogPostFields {
  /** Name */
  readonly name: string;
  /** Thumbnail */
  readonly thumbnail: BetterCMSImage;
  /** Content */
  readonly content: RichText;
  /** Author */
  readonly author?: string;
  /** Published */
  readonly published?: string;
  /** Blog Number */
  readonly blog_number?: number;
  /** Is Featured */
  readonly is_featured?: boolean;
}

/**
 * Case Study
 * Model slug: `case-study`
 */
export interface CaseStudyFields {
  /** Title */
  readonly title?: string;
  /** Client */
  readonly client?: string;
  /** Summary */
  readonly summary?: string;
  /** Cover Image */
  readonly coverImage?: BetterCMSImage;
  /** Body */
  readonly body?: RichText;
  /** Metrics */
  readonly metrics?: {
    readonly repeatable?: Array<{
      /** Value */
      readonly value?: string;
      /** Label */
      readonly label?: string;
    }>;
  };
  /** Published Date */
  readonly publishedDate?: string;
}

/**
 * Contact
 * Model slug: `contact`
 */
export interface ContactFields {
  /** Eyebrow */
  readonly eyebrow?: string;
  /** Hero Title */
  readonly heroTitle?: string;
  /** Hero Subtitle */
  readonly heroSubtitle?: string;
}

/**
 * Home
 * Model slug: `home`
 */
export interface HomeFields {
  /** Eyebrow */
  readonly eyebrow?: string;
  /** Hero Title */
  readonly heroTitle?: string;
  /** Hero Subtitle */
  readonly heroSubtitle?: string;
  /** Hero Image */
  readonly heroImage?: BetterCMSImage;
  /** Primary Cta Text */
  readonly primaryCtaText?: string;
  /** Primary Cta Href */
  readonly primaryCtaHref?: string;
  /** Secondary Cta Text */
  readonly secondaryCtaText?: string;
  /** Secondary Cta Href */
  readonly secondaryCtaHref?: string;
  /** Stats */
  readonly stats?: {
    readonly repeatable?: Array<{
      /** Value */
      readonly value?: string;
      /** Label */
      readonly label?: string;
    }>;
  };
  /** Features Heading */
  readonly featuresHeading?: string;
  /** Features */
  readonly features?: {
    readonly repeatable?: Array<{
      /** Icon */
      readonly icon?: string;
      /** Title */
      readonly title?: string;
      /** Body */
      readonly body?: string;
    }>;
  };
  /** Logos */
  readonly logos?: {
    readonly repeatable?: Array<{
      /** Name */
      readonly name?: string;
    }>;
  };
  /** Testimonials */
  readonly testimonials?: {
    readonly repeatable?: Array<{
      /** Quote */
      readonly quote?: string;
      /** Author Name */
      readonly authorName?: string;
      /** Author Role */
      readonly authorRole?: string;
      /** Avatar */
      readonly avatar?: BetterCMSImage;
    }>;
  };
  /** Cta Heading */
  readonly ctaHeading?: string;
  /** Cta Body */
  readonly ctaBody?: string;
  /** Cta Button Text */
  readonly ctaButtonText?: string;
  /** Cta Button Href */
  readonly ctaButtonHref?: string;
}

/**
 * Site
 * Model slug: `site`
 */
export interface SiteFields {
  /** Brand Name */
  readonly brandName?: string;
  /** Nav Links */
  readonly navLinks?: {
    readonly repeatable?: Array<{
      /** Label */
      readonly label?: string;
      /** Href */
      readonly href?: string;
    }>;
  };
  /** Footer Tagline */
  readonly footerTagline?: string;
  /** Socials */
  readonly socials?: {
    readonly repeatable?: Array<{
      /** Label */
      readonly label?: string;
      /** Href */
      readonly href?: string;
    }>;
  };
  /** Seo Title */
  readonly seoTitle?: string;
  /** Seo Description */
  readonly seoDescription?: string;
  /** Og Image */
  readonly ogImage?: BetterCMSImage;
  /** Twitter Handle */
  readonly twitterHandle?: string;
  /** Custom Head Html */
  readonly customHeadHtml?: string;
  /** Custom Body End Html */
  readonly customBodyEndHtml?: string;
}
/**
 * Registry mapping each model slug to its typed fields. The Next adapter uses this to
 * type `getEntry("blog", ...)` by slug — autocomplete and exhaustiveness for free.
 */
export interface BetterCMSSchema {
  readonly "about": AboutFields;
  readonly "author": AuthorFields;
  readonly "authors": AuthorsFields;
  readonly "blog-post": BlogPostFields;
  readonly "case-study": CaseStudyFields;
  readonly "contact": ContactFields;
  readonly "home": HomeFields;
  readonly "site": SiteFields;
}

/** Union of all model slugs. */
export type BetterCMSModelSlug = keyof BetterCMSSchema;
