// ⚠️  AUTO-GENERATED by @bettercms-ai/codegen v0.2.0 — DO NOT EDIT.
// Live Preview field bindings. Regenerate with: npx @bettercms-ai/codegen --bindings-out <path>
// Spread these onto the elements that render your content; they emit
// data-bcms-field/data-bcms-kind only when the site is built with BCMS_ANNOTATE set.

/**
 * True when this site is built for Live Preview annotation. Set `BCMS_ANNOTATE=1`
 * in the preview build only; unset (the default) ships zero binding attributes.
 * Read defensively so the module is safe in any runtime (browser, Node, edge).
 */
const BCMS_ANNOTATE: boolean = (() => {
  try {
    const v = (globalThis as { process?: { env?: Record<string, string | undefined> } })
      .process?.env?.BCMS_ANNOTATE;
    return v != null && v !== "" && v !== "0" && v !== "false";
  } catch {
    return false;
  }
})();

/**
 * Binding attributes for a CMS-bound element. Spread onto the element that renders a
 * field: `<h1 {...bcmsField("title", "text")}>`. Returns `{}` unless BCMS_ANNOTATE
 * is set, so production markup is untouched.
 */
export function bcmsField(path: string, kind: string): Record<string, string> {
  return BCMS_ANNOTATE ? { "data-bcms-field": path, "data-bcms-kind": kind } : {};
}

/**
 * Field bindings keyed by model slug. Spread a binding onto the element that renders
 * that field. Arrays expose `$(i)` for the item element and one accessor per
 * (one-level) sub-field; primitive arrays expose `value(i)` for the item's scalar.
 */
export const bcms = {
  "about": {
    eyebrow: bcmsField("eyebrow", "text"),
    heroTitle: bcmsField("heroTitle", "text"),
    heroSubtitle: bcmsField("heroSubtitle", "text"),
    heroImage: bcmsField("heroImage", "image"),
    storyTitle: bcmsField("storyTitle", "text"),
    story: bcmsField("story", "richtext"),
    values: {
      $: (i: number) => bcmsField("values[" + i + "]", "array"),
      title: (i: number) => bcmsField("values[" + i + "].title", "text"),
      body: (i: number) => bcmsField("values[" + i + "].body", "text"),
    },
    stats: {
      $: (i: number) => bcmsField("stats[" + i + "]", "array"),
      value: (i: number) => bcmsField("stats[" + i + "].value", "text"),
      label: (i: number) => bcmsField("stats[" + i + "].label", "text"),
    },
    team: bcmsField("team", "text"),
  },
  "author": {
    name: bcmsField("name", "text"),
    role: bcmsField("role", "text"),
    bio: bcmsField("bio", "text"),
    avatar: bcmsField("avatar", "image"),
  },
  "authors": {
    name: bcmsField("name", "text"),
    bio: bcmsField("bio", "text"),
  },
  "blog-post": {
    name: bcmsField("name", "text"),
    thumbnail: bcmsField("thumbnail", "image"),
    content: bcmsField("content", "richtext"),
    author: bcmsField("author", "text"),
    published: bcmsField("published", "date"),
    blog_number: bcmsField("blog_number", "number"),
    is_featured: bcmsField("is_featured", "boolean"),
  },
  "case-study": {
    title: bcmsField("title", "text"),
    client: bcmsField("client", "text"),
    summary: bcmsField("summary", "text"),
    coverImage: bcmsField("coverImage", "image"),
    body: bcmsField("body", "richtext"),
    metrics: {
      $: (i: number) => bcmsField("metrics[" + i + "]", "array"),
      value: (i: number) => bcmsField("metrics[" + i + "].value", "text"),
      label: (i: number) => bcmsField("metrics[" + i + "].label", "text"),
    },
    publishedDate: bcmsField("publishedDate", "text"),
  },
  "contact": {
    eyebrow: bcmsField("eyebrow", "text"),
    heroTitle: bcmsField("heroTitle", "text"),
    heroSubtitle: bcmsField("heroSubtitle", "text"),
  },
  "home": {
    hero: {
      eyebrow: bcmsField("hero.eyebrow", "text"),
      heroTitle: bcmsField("hero.heroTitle", "text"),
      heroSubtitle: bcmsField("hero.heroSubtitle", "text"),
      primaryCtaText: bcmsField("hero.primaryCtaText", "text"),
      primaryCtaHref: bcmsField("hero.primaryCtaHref", "text"),
      secondaryCtaText: bcmsField("hero.secondaryCtaText", "text"),
      secondaryCtaHref: bcmsField("hero.secondaryCtaHref", "text"),
    },
    features: {
      $: (i: number) => bcmsField("features[" + i + "]", "array"),
      heading: (i: number) => bcmsField("features[" + i + "].heading", "text"),
      description: (i: number) => bcmsField("features[" + i + "].description", "text"),
    },
    stats: {
      $: (i: number) => bcmsField("stats[" + i + "]", "array"),
      statValue: (i: number) => bcmsField("stats[" + i + "].statValue", "text"),
      description: (i: number) => bcmsField("stats[" + i + "].description", "text"),
    },
    testimonials: {
      $: (i: number) => bcmsField("testimonials[" + i + "]", "array"),
      testimonial: (i: number) => bcmsField("testimonials[" + i + "].testimonial", "text"),
      clientName: (i: number) => bcmsField("testimonials[" + i + "].clientName", "text"),
      designation: (i: number) => bcmsField("testimonials[" + i + "].designation", "text"),
    },
    cta: {
      ctaHeading: bcmsField("cta.ctaHeading", "text"),
      ctaBody: bcmsField("cta.ctaBody", "text"),
      ctaButtonText: bcmsField("cta.ctaButtonText", "text"),
      ctaButtonHref: bcmsField("cta.ctaButtonHref", "text"),
    },
  },
  "site": {
    brandName: bcmsField("brandName", "text"),
    navLinks: {
      $: (i: number) => bcmsField("navLinks[" + i + "]", "array"),
      label: (i: number) => bcmsField("navLinks[" + i + "].label", "text"),
      href: (i: number) => bcmsField("navLinks[" + i + "].href", "text"),
    },
    footerTagline: bcmsField("footerTagline", "text"),
    socials: {
      $: (i: number) => bcmsField("socials[" + i + "]", "array"),
      label: (i: number) => bcmsField("socials[" + i + "].label", "text"),
      href: (i: number) => bcmsField("socials[" + i + "].href", "text"),
    },
    seoTitle: bcmsField("seoTitle", "text"),
    seoDescription: bcmsField("seoDescription", "text"),
    ogImage: bcmsField("ogImage", "image"),
    twitterHandle: bcmsField("twitterHandle", "text"),
    customHeadHtml: bcmsField("customHeadHtml", "text"),
    customBodyEndHtml: bcmsField("customBodyEndHtml", "text"),
  },
} as const;
